# Generated by Django 4.2 on 2023-08-03 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Class",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "class_name",
                    models.TextField(db_column="class_name", max_length=20, null=True),
                ),
                ("class_sem", models.TextField(db_column="class_sem", max_length=20)),
            ],
            options={
                "db_table": "classes",
            },
        ),
        migrations.CreateModel(
            name="Fee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("class_name", models.TextField(db_column="class_name", max_length=20)),
                (
                    "tuition_fee",
                    models.TextField(db_column="tuition_fee", max_length=10, null=True),
                ),
                (
                    "special1",
                    models.TextField(
                        db_column="special_fee1", max_length=10, null=True
                    ),
                ),
                (
                    "special2",
                    models.TextField(
                        db_column="special_fee2", max_length=10, null=True
                    ),
                ),
                (
                    "special3",
                    models.TextField(
                        db_column="special_fee3", max_length=10, null=True
                    ),
                ),
                (
                    "deposit_fee",
                    models.TextField(db_column="deposit", max_length=10, null=True),
                ),
                (
                    "sem1_fee",
                    models.TextField(db_column="sem_fee1", max_length=10, null=True),
                ),
                (
                    "sem2_fee",
                    models.TextField(db_column="sem_fee2", max_length=10, null=True),
                ),
                (
                    "sem3_fee",
                    models.TextField(db_column="sem_fee3", max_length=10, null=True),
                ),
                (
                    "sem4_fee",
                    models.TextField(db_column="sem_fee4", max_length=10, null=True),
                ),
                (
                    "sem5_fee",
                    models.TextField(db_column="sem_fee5", max_length=10, null=True),
                ),
                (
                    "sem6_fee",
                    models.TextField(db_column="sem_fee6", max_length=10, null=True),
                ),
            ],
            options={
                "db_table": "fees",
            },
        ),
        migrations.CreateModel(
            name="Main",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("class_name", models.TextField(db_column="class", max_length=20)),
            ],
            options={
                "db_table": "main",
            },
        ),
        migrations.CreateModel(
            name="Notice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "class_notice",
                    models.TextField(db_column="class_notice", max_length=200),
                ),
            ],
            options={
                "db_table": "notices",
            },
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("admin_name", models.TextField(db_column="ad_name", max_length=20)),
                ("admin_id", models.TextField(db_column="ad_id", max_length=10)),
                ("admin_dob", models.DateField(db_column="ad_dob")),
                (
                    "admin_gender",
                    models.TextField(db_column="ad_gender", max_length=20),
                ),
                ("admin_email", models.TextField(db_column="ad_email", max_length=30)),
                (
                    "admin_password",
                    models.TextField(db_column="ad_password", max_length=20, null=True),
                ),
                (
                    "status",
                    models.TextField(
                        db_column="status",
                        default="to_approve",
                        max_length=20,
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "staff",
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("class_sub", models.TextField(db_column="sub_name", max_length=20)),
                ("class_subid", models.TextField(db_column="sub_id", max_length=20)),
                (
                    "class_teacher",
                    models.TextField(db_column="teacher_name", max_length=20),
                ),
                (
                    "class_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admin1.class",
                    ),
                ),
            ],
            options={
                "db_table": "subjects",
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_name", models.TextField(db_column="stu_name", max_length=20)),
                ("student_roll", models.TextField(db_column="stu_roll", max_length=20)),
                (
                    "student_email",
                    models.TextField(db_column="stu_email", max_length=30),
                ),
                (
                    "student_gender",
                    models.TextField(db_column="stu_gender", max_length=20),
                ),
                ("student_dob", models.DateField(db_column="stu_dob")),
                (
                    "student_password",
                    models.TextField(db_column="stu_password", max_length=30),
                ),
                ("otp", models.TextField(db_column="otp", max_length=10, null=True)),
                (
                    "status",
                    models.TextField(
                        db_column="status", default="", max_length=50, null=True
                    ),
                ),
                (
                    "student_class",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admin1.class",
                    ),
                ),
            ],
            options={
                "db_table": "student",
            },
        ),
        migrations.CreateModel(
            name="Results",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "marks",
                    models.TextField(db_column="marks", default=100, max_length=10),
                ),
                (
                    "total_marks",
                    models.TextField(db_column="total_marks", default=0, max_length=10),
                ),
                (
                    "grade",
                    models.TextField(db_column="grade", default="", max_length=5),
                ),
                (
                    "class_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admin1.class",
                    ),
                ),
                (
                    "student_roll",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admin1.student",
                    ),
                ),
                (
                    "sub_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admin1.subject",
                    ),
                ),
            ],
            options={
                "db_table": "results",
            },
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day1", models.IntegerField(db_column="day1", default=0)),
                ("day2", models.IntegerField(db_column="day2", default=0)),
                ("day3", models.IntegerField(db_column="day3", default=0)),
                ("day4", models.IntegerField(db_column="day4", default=0)),
                ("day5", models.IntegerField(db_column="day5", default=0)),
                ("day6", models.IntegerField(db_column="day6", default=0)),
                ("day7", models.IntegerField(db_column="day7", default=0)),
                ("day8", models.IntegerField(db_column="day8", default=0)),
                ("day9", models.IntegerField(db_column="day9", default=0)),
                ("day10", models.IntegerField(db_column="day10", default=0)),
                ("day11", models.IntegerField(db_column="day11", default=0)),
                ("day12", models.IntegerField(db_column="day12", default=0)),
                ("day13", models.IntegerField(db_column="day13", default=0)),
                ("day14", models.IntegerField(db_column="day14", default=0)),
                ("day15", models.IntegerField(db_column="day15", default=0)),
                ("day16", models.IntegerField(db_column="day16", default=0)),
                ("day17", models.IntegerField(db_column="day17", default=0)),
                ("day18", models.IntegerField(db_column="day18", default=0)),
                ("day19", models.IntegerField(db_column="day19", default=0)),
                ("day20", models.IntegerField(db_column="day20", default=0)),
                ("day21", models.IntegerField(db_column="day21", default=0)),
                ("day22", models.IntegerField(db_column="day22", default=0)),
                ("day23", models.IntegerField(db_column="day23", default=0)),
                ("day24", models.IntegerField(db_column="day24", default=0)),
                ("day25", models.IntegerField(db_column="day25", default=0)),
                ("day26", models.IntegerField(db_column="day26", default=0)),
                ("day27", models.IntegerField(db_column="day27", default=0)),
                ("day28", models.IntegerField(db_column="day28", default=0)),
                ("day29", models.IntegerField(db_column="day29", default=0)),
                ("day30", models.IntegerField(db_column="day30", default=0)),
                ("day31", models.IntegerField(db_column="day31", default=0)),
                (
                    "present",
                    models.IntegerField(db_column="present", default=0, null=True),
                ),
                (
                    "absent",
                    models.IntegerField(db_column="absent", default=0, null=True),
                ),
                (
                    "class_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admin1.class",
                    ),
                ),
                (
                    "student_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admin1.student",
                    ),
                ),
            ],
            options={
                "db_table": "attendance",
            },
        ),
    ]
