# Generated by Django 4.2 on 2023-08-03 07:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin1", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="month",
            field=models.CharField(db_column="month", max_length=20, null=True),
        ),
    ]
