# Generated by Django 4.2 on 2023-08-03 10:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("admin1", "0003_alter_attendance_absent_alter_attendance_present"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attendance",
            name="absent",
        ),
        migrations.RemoveField(
            model_name="attendance",
            name="present",
        ),
    ]
