# Generated by Django 4.2 on 2023-08-04 09:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin1", "0005_month"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="credit",
            field=models.IntegerField(db_column="credit", default=1, max_length=10),
        ),
    ]
