# Generated by Django 4.2 on 2023-08-04 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("admin1", "0006_subject_credit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="class",
            name="class_name",
        ),
        migrations.AddField(
            model_name="class",
            name="class_id",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="admin1.main"
            ),
        ),
    ]
