# Generated by Django 4.2 on 2023-08-04 10:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin1", "0007_remove_class_class_name_class_class_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="class",
            name="class_id",
        ),
        migrations.AddField(
            model_name="class",
            name="class_name",
            field=models.TextField(db_column="class_name", max_length=20, null=True),
        ),
    ]
