# Generated by Django 4.2 on 2023-08-04 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("admin1", "0008_remove_class_class_id_class_class_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="student_sem",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="admin1.class",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="student_class",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="admin1.main"
            ),
        ),
    ]
