# Generated by Django 4.2 on 2023-08-04 11:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin1", "0009_student_student_sem_alter_student_student_class"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="student_class",
            field=models.TextField(db_column="student_class", max_length=20, null=True),
        ),
    ]
