# Generated by Django 4.2 on 2023-08-15 06:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin1", "0012_results_grade_point_alter_subject_credit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="month",
            field=models.IntegerField(db_column="month", max_length=20, null=True),
        ),
    ]
